// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIDuFUQeSLTbh9WfjRmCq9MzLmxB5Li5I',
    appId: '1:423699553524:web:d7f7a85261abecdfab92a1',
    messagingSenderId: '423699553524',
    projectId: 'test-work-chat',
    authDomain: 'test-work-chat.firebaseapp.com',
    storageBucket: 'test-work-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsjJAln6h4RedJ-uv6Lid7dPBn3cH-ILU',
    appId: '1:423699553524:android:194acadd2f66f926ab92a1',
    messagingSenderId: '423699553524',
    projectId: 'test-work-chat',
    storageBucket: 'test-work-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-5TmJKWGOU8QYStJwvAxlqRGjYooMTsM',
    appId: '1:423699553524:ios:c43624f136d3c1c3ab92a1',
    messagingSenderId: '423699553524',
    projectId: 'test-work-chat',
    storageBucket: 'test-work-chat.appspot.com',
    iosClientId: '423699553524-8iu6vqc7sgort563a5kfdldu6km00n9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatTestWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-5TmJKWGOU8QYStJwvAxlqRGjYooMTsM',
    appId: '1:423699553524:ios:c43624f136d3c1c3ab92a1',
    messagingSenderId: '423699553524',
    projectId: 'test-work-chat',
    storageBucket: 'test-work-chat.appspot.com',
    iosClientId: '423699553524-8iu6vqc7sgort563a5kfdldu6km00n9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatTestWork',
  );
}
